### PR TITLE
serde: remove serde implementation and use mdsf

### PR DESCRIPTION
**Pull request by belochub**

### CODE REVIEW

**Comment by lundibundi** [comment]
@belochub did you perhaps forgot to remove `test/fixtures/todo/serde/` or do we need them?

**Comment by belochub** [comment]
@lundibundi, @aqrln, @nechaido I've updated the `mdsf` package to fix building on Windows systems, PTAL.

**Comment by nechaido** [comment]
ping @aqrln

**Comment by belochub** [comment]
Landed in https://github.com/metarhia/jstp/commit/c988c0bfe4d70d5ede273bb52d41fae948be68f6.

**Pull request closed without merging**
