### PR TITLE
tcp: fix URL parsing in client creation

### PR DESCRIPTION
**Pull request by belochub**

### CODE REVIEW

**Comment by belochub** [comment]
Landed in 8c72d3e5803c03672181e283e5f73f39b3323c45.

**Comment by belochub** [comment]
@aqrln, yes, you are right. Should I update the commit?

**Comment by aqrln** [comment]
@belochub yeah, sure. Force-push it before it's too late :)

**Comment by belochub** [comment]
@aqrln, I am sorry for the inconvenience.
Landed in 0b3a8cdb88c263dec3f20c8eaf1235ae81274734.

**Comment by aqrln** [comment]
@belochub no worries, thanks!

**Pull request closed without merging**
