### PR TITLE
add arrow-parens rule to eslint

### PR DESCRIPTION
**Pull request by lundibundi**
Force eslint to throw an error on arrow function with braces
but without parens, this will make code a bit more consistent

### CODE REVIEW

**Comment by aqrln** [comment]
I'd actually prefer if the parens were not necessary for one-liners, but would not be treated as errors. Seems like that's exactly the reason I did not enable this rule 😕

**Comment by aqrln** [comment]
@lundibundi can you please fix the linter errors and add the "lint:" prefix to the commit message? I'd like to see how those functions will look like and how will it impact readability.

**Comment by lundibundi** [comment]
I guess it's better to keep track of functions with braces but without parens, as is rare to use parens with simple functions

**Comment by lundibundi** [comment]
@aqrln done

**Comment by aqrln** [comment]
Landed in 29938d2e5599f5bdaf36fd93b6c3ee5745695c71.

**Pull request closed without merging**
