### PR TITLE
parser: remove special case for '\0' literal

### PR DESCRIPTION
**Pull request by belochub**
Remove special case for '\0' in control character parsing.

### CODE REVIEW

**Comment by aqrln** [comment]
Oh, sweet. Looks like we don't have tests for escape sequences.

**Comment by aqrln** [comment]
Well, I think we can be pretty sure it doesn't introduce any regression since the change is trivial. But we must put writing proper tests for existing code on our agenda and do it ASAP. Since that, each PR will be required to add tests for any new or updated functionality.

**Comment by belochub** [comment]
@aqrln let's start with rewriting existing tests from scratch to make them easier to read and update.

**Comment by belochub** [comment]
Landed in ae7a557cebde953df4178d3b4ca167646e352478.

**Comment by aqrln** [comment]
Labeled it `semver-major` because it isn't a backward-compatible change.

**Pull request closed without merging**
