### PR TITLE
deps: update dependencies

### PR DESCRIPTION
**Pull request by aqrln**
/cc @nechaido do review that `yargs` update doesn't break anything.

### CODE REVIEW

**Comment by aqrln** [comment]
Also, there's a pending update to the latest version of `eslint-config-metarhia`, but there are some stylistic changes that must be applied, and for some reason, tests are failing for me when I do that, so I guess I'll do that in a separate PR.

**Comment by nechaido** [comment]
@aqrln could you please update this PR?

**Comment by belochub** [comment]
@lundibundi, I think, we can do this in another PR.

**Comment by belochub** [comment]
Landed in 65e502cce3c733eac1a71a1adef6486958253c1c.

**Pull request closed without merging**
