### PR TITLE
Added link to  Visual Studio Code JSTP plugin

### PR DESCRIPTION
**Pull request by ernado-x**

### CODE REVIEW

**Comment by aqrln** [comment]
Thanks for the contribution! I'm not sure about the need for this plugin though. As far as I can see, it adds syntax highlighting for files with extensions like `.jstp`, `.jsrs` and stuff, but we decided to drop them and use just plain `.js` almost a year ago, and now we are directing towards making our data format fully compliant to the JSON5 specs, so `.json5` will be used as the extension.

**Comment by ernado-x** [comment]
It is very good that you moving in global standards direction! But in this case, you have very outdated documentations here - https://metarhia.github.io/JSTP/data-formats/ and old examples here - https://github.com/metarhia/JSTP/tree/master/examples/data-formats. It very confused me as developer which want to investigate your protocol.

**Comment by aqrln** [comment]
@ernado-x yeah, the lack of up-to-date documentation is definitely an issue :)
It is one of our priorities too, right after writing decent tests and increasing the test coverage to an acceptable value, which we're working on right now. One may expect us to start writing docs and examples in a week or two.

**Comment by aqrln** [comment]
/cc @metarhia/jstp

I'd want to hear some input from other collaborators about whether this is something that we want. I'd say no and go ahead saying thanks again and closing the PR, but maybe it's just me.

**Comment by aqrln** [comment]
Closing the PR based on the conversation above and thumb-up votes. Please let me know if you'd like to contribute to the project in any other ways. Thanks!

**Pull request closed without merging**
