### PR TITLE
deps: update dependencies

### PR DESCRIPTION
**Pull request by aqrln**

### CODE REVIEW

**Comment by lundibundi** [comment]
I think it's time to update them once again =).

**Comment by aqrln** [comment]
@lundibundi done, PTAL.

**Comment by aqrln** [comment]
FYI: I have not updated remark to 7.x yet, because there's not much point in doing so until #282 will have been resolved (duh, I have completely forgotten about that one, gonna do it soon). There'll be a single PR that will update the remark config to what remark@7 expects, together with updating the package.

**Comment by belochub** [comment]
Landed in https://github.com/metarhia/jstp/commit/0d63a0fcf03f484101f9538df82ed60ffc75d56a.

**Pull request closed without merging**
