### PR TITLE
(v0.5 backport) lint: backport bitHoud-related commits

### PR DESCRIPTION
**Pull request by aqrln**
This PR fixes failing bitHoud checks for v0.5.

### CODE REVIEW

**Comment by aqrln** [comment]
@belochub bitHoud is now happy, can you please take a look at this PR?

**Comment by belochub** [comment]
CI fails with some errors during installation. Can you check this out, please?

**Comment by aqrln** [comment]
Ugh... messed up with resolving conflicts in cc78133471133ece38f3e55da0f05308c5c5dcaf.

**Comment by aqrln** [comment]
Landed in 52f273d8a6309f04dbe972322aadfa150ede05e2, 8d66c79338c1d7c8fbec76a7a6b207dcdfeb3d2a, bae89505fec895ad8a0f458be1a8ebf6ecd1f5ab, d40370b19b70c7477932576b3d3d2beab4582ffe and e28334dc689970637ae38bd27666391af32d4fa6.

**Comment by aqrln** [comment]
For the record: Travis and bitHound linter passing, bitHound dependency checker complains at stale webpack devDependency we cannot upgrade for v0.5.

**Pull request closed without merging**
