### PR TITLE
v0.6.6 proposal

### PR DESCRIPTION
**Pull request by aqrln**
## Version 0.6.6 (2017-02-20, @aqrln)

This is mostly a bugfix release. Additionally, parser performance is improved.

Notable changes:

 * **server:** clean internal structures on close *(Alexey Orlenko)* [#59](https://github.com/metarhia/JSTP/pull/59)
 * **src,build:** add missing header *(Mykola Bilochub)* [#64](https://github.com/metarhia/JSTP/pull/64)
 * **parser:** make parser single-pass *(Mykola Bilochub)* [#61](https://github.com/metarhia/JSTP/pull/61)
 * **lib:** fix behavior with util.inspect *(Alexey Orlenko)* [#72](https://github.com/metarhia/JSTP/pull/72)
 * **parser:** fix bug causing node to crash *(Mykola Bilochub)* [#75](https://github.com/metarhia/JSTP/pull/75)
 * **server:** handle connection errors before handshake *(Alexey Orlenko)* [#78](https://github.com/metarhia/JSTP/pull/78)
 * **connection:** close connection on transport error *(Alexey Orlenko)* [#78](https://github.com/metarhia/JSTP/pull/78)

All changes:

 * **server:** clean internal structures on close *(Alexey Orlenko)* [#59](https://github.com/metarhia/JSTP/pull/59)
 * **src,build:** add missing header *(Mykola Bilochub)* [#64](https://github.com/metarhia/JSTP/pull/64)
 * **src:** add curly braces in `switch` statements *(Mykola Bilochub)* [#62](https://github.com/metarhia/JSTP/pull/62)
 * **build:** fail CI if native addon build fails *(Alexey Orlenko)* [#65](https://github.com/metarhia/JSTP/pull/65)
 * **parser:** make parser single-pass *(Mykola Bilochub)* [#61](https://github.com/metarhia/JSTP/pull/61)
 * **src:** fix single-line comment spacing *(Mykola Bilochub)* [#67](https://github.com/metarhia/JSTP/pull/67)
 * **parser:** improve string parsing *(Mykola Bilochub)* [#66](https://github.com/metarhia/JSTP/pull/66)
 * **src:** fix inconsistency in empty string creation *(Mykola Bilochub)* [#70](https://github.com/metarhia/JSTP/pull/70)
 * **doc:** document protocol versioning policy *(Alexey Orlenko)* [#56](https://github.com/metarhia/JSTP/pull/56)
 * **lib:** fix behavior with util.inspect *(Alexey Orlenko)* [#72](https://github.com/metarhia/JSTP/pull/72)
 * **deps,build:** update webpack to 2.x *(Alexey Orlenko)* [#73](https://github.com/metarhia/JSTP/pull/73)
 * **build,test:** avoid unnecessary recompiling *(Alexey Orlenko)* [#74](https://github.com/metarhia/JSTP/pull/74)
 * **doc:** update badges in README.md and doc/index.md *(Alexey Orlenko)* [#71](https://github.com/metarhia/JSTP/pull/71)
 * **parser:** fix bug causing node to crash *(Mykola Bilochub)* [#75](https://github.com/metarhia/JSTP/pull/75)
 * **tools:** automate the release preparation *(Alexey Orlenko)* [#77](https://github.com/metarhia/JSTP/pull/77)
 * **server:** handle connection errors before handshake *(Alexey Orlenko)* [#78](https://github.com/metarhia/JSTP/pull/78)
 * **connection:** close connection on transport error *(Alexey Orlenko)* [#78](https://github.com/metarhia/JSTP/pull/78)

### CODE REVIEW

**Comment by aqrln** [comment]
@belochub I don't think it is. `error` events on `Connection` instances are mostly fired when an underlying socket closes because of an error, so the application code surely cannot and couldn't rely on the connection still being active in an error handler.

**Comment by belochub** [comment]
@aqrln, I am just worried if someone was listening for `connectionError` event to close the connection, and now with this change connection will be closed twice.

**Comment by belochub** [comment]
@aqrln if this won't cause any problems, you can proceed with the release.

**Comment by aqrln** [comment]
@belochub in most cases a connection would already be closed in a `connectionError` handler :) FWIW, I do agree with your point that it may be a breaking change for someone and I'd be cautious with landing this change if we were popular, but I'm pretty sure it won't break any of our code and even if there are third-party users, we can't really guarantee anything about versions <1.0.0 though we do our best to be compatible (which we kinda actually do for ourselves too). So I think we should land this on v0.6 so that Impress gets a security update.

**Comment by aqrln** [comment]
Yeah, and the only thing that can be broken at all is the situation when anyone writes data to a connection in the `error` event handler which was caused by a parsing error, which certainly cannot be qualified as correct usage.

**Comment by aqrln** [comment]
Version 0.6.6 is merged to `v0.6`, tagged and published to NPM, browser build on site is updated too.
/cc @belochub @tshemsedinov

**Pull request merged**
